Adding custom color parameter for select confirm button
msalman2890/flutter_custom_month_picker pull request #4
Opened 2024-05-03 01:46 UTC by riVFerd

Adding additional parameter "selectTextColor" to avoid select confirm button text being unseen like below example:

![image](https://github.com/msalman2890/flutter_custom_month_picker/assets/88952885/6504a658-e26a-402d-b8ca-a9dade704d8b)

2024-05-03 21:14 UTC, msalman2890 commented on lib/src/views/custom_month_picker.dart
Can you please include just required changes instead of overall formatting?

2024-05-03 21:18 UTC, msalman2890 requested changes
Can you please include just required changes instead of overall formatting?

2024-05-03 22:03 UTC, riVFerd commented
Sure, here's the updated version without overall formatting

2024-05-05 15:08 UTC, msalman2890 approved these changes

2024-05-05 15:08 UTC, merged